### ISSUE TITLE
Re-add new packages from CRAN

### ISSUE THREAD

**Issue by hadley** [r-lib/revdepcheck#124]
It would be useful to have an easy way to just test the packages that have been added to CRAN since the last run. (This is useful for testthat which gains ~10 new revdeps per week)

**Comment by gaborcsardi** [comment]
This will require some new data in the DB, because we need to know the packages that were considered already for revdepchecking. E.g. if I `revdep_rm()-d` some packages, I don't want to re-add them with the new `revdep_add_new()`.

So we'll have a second column for the todo table, to have some kind of status, and update that by the checks, and `revdep_add*` and `revdep_rm()`.

Then `revdep_update()` (?) can just look up the revdeps again and update the todo table, to add new packages, and set updated packages to "todo" status.

**Comment by hadley** [comment]
Yeah, I like it.
