### ISSUE TITLE
Deal with packages that launch Tcl/Tk widgets

### ISSUE THREAD

**Issue by jennybc** [r-lib/revdepcheck#142]
During the revdepchecks for readxl, I dealt with zooaRchGUI and dynBiplotGUI. Both appear to launch Tcl/Tk widgets during R CMD check. When I check them "manually", for example, XQuartz has been launched. In the case of dynBiplotGUI, I literally see the widgets popping up and disappearing.

`revdep_check()` gets stuck on these and eventually crashes R or times out. Even a faster and more elegant failure would be very welcome.

**Comment by jennybc** [comment]
Next readxl release. Same XQuartz experience.

**Comment by gaborcsardi** [comment]
This is because we unset the `DISPLAY` env var, otherwise graphics and tk windows pop up all the time. This is not new, devtools used to do the same: https://github.com/r-lib/revdepcheck/blame/9304386f8eec0e7bf7b91645e106b178d3b77dc8/R/check.R#L82

I don't think there is an easy way to auto-detect tk. I can make unsetting `DISPLAY` optional if you want, but I don't think that will be a pleasant experience. 

In general I think the packages should pass the check without X11, so I consider this bugs in zooaRchGUI etc.

**Comment by jennybc** [comment]
It's a shame this doesn't evoke the same CRAN reaction as trying to access the clipboard or the internet.

**Comment by bbolker** [comment]
Any chance of making this work with [Xvfb](https://en.wikipedia.org/wiki/Xvfb) where possible? (See [here](https://github.com/travis-ci/travis-ci/issues/7313#issuecomment-279914149) for OSX discussion ...)

**Comment by gaborcsardi** [comment]
@bbolker You can try that if you like. For Xvfb, we don't need to change revdepcheck, except for removing the `DISPLAY` reset. Then you can just start Xvfb, set `DISPLAY` in your terminal or the main R session accordingly, and run the checks.

**Comment by hadley** [comment]
If you can come up with a mechanism to turn tcl/tk off, we'd happily apply it. But that's probably going to take some investigation.
