### ISSUE TITLE
workers that have timed out are killed, but do not start on next task

### ISSUE THREAD

**Issue by schloerke** [r-lib/revdepcheck#183]
If the timeout time is reached, workers are killed. However, the status will continue to state that the worker is checking. This prevents other revdep checks from being completed.

**Comment by jennybc** [comment]
I think I am suffering from this as well. I have extremely limited bandwidth right now and as soon as I encounter `num_workers` packages that timeout, I think nothing is actually happening anymore.

**Comment by jennybc** [comment]
I'm revisiting the revdep checks that caused me to weigh in on this thread. It's going much better because my internet access is vastly better and some of the revdeps have fixed their problems.

But I notice that one of the problem packages has been sitting on its worker (1 of 4) since the very start. It's the only package remaining.  ETA for the overall job has been 1m for >20 mins and I'm just going to kill this. But I think there is still something wrong, because this specific check should have timed out a long time ago. It's been running for much longer than the 10 minute timeout. The package in question is BIOMASS (wrt to usethis), in case it ends up being something unique to this pair of packages. Is it timing out and then getting restarted?
