### ISSUE TITLE
Do not mark package as done if only old/new is done

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/revdepcheck#198]

**Comment by lionel-** [comment]
Does this conflict with the idea of running all old checks under trunk r-source and then, separately, all new checks under a patched r-source?

**Comment by gaborcsardi** [comment]
It does indeed, but that did not work before this change, either.

**Comment by lionel-** [comment]
Do you have any plans for supporting (a) higher-order revdep checks (without duplicate checks, and with the provenance of each revdep indicated in the Rmd table), (b) samples of revdep checks, and (c) separate old/new runs?

I've been running a fork of revdepcheck for 2 years because I need (a) for checking packages like rlang. I'll need the latter two features for checking R core patches against samples of CRAN packages. The PRs you have closed without discussion implemented (a), (b), and planned for (c).

**Comment by gaborcsardi** [comment]
(a) you can add any packages to the todo list, so this should be covered

(b) again, if you want to sample, then I think you can use `revdep_add()` and/or `revdep_rm()`.

(c) this is kind of complicated, because R being a rolling release, the set of dependency versions is different if you don't do the old/new runs at the same time. So it is hard to compare. revdepcheck tries hard to make sure that the only difference between the old and new runs is the package you are revde_pcheck()-ing, and with this feature we would need to give up this assumption. Also, this is not really a revdep check, but just checking a bunch of packages, one after the other. So I think it would be best to introduce a new function for this.

**Comment by lionel-** [comment]
Ideally I need groups in the output tables to make sense of the results (revdeps for rlang, then revdeps for dplyr, purrr, etc). The idea of allowing tibbles of groups was to unify the CRAN/bioc and higher-order revdep groupings, or any arbitrary grouping really, then we use a single report function for everything.

Alternatively separate files like `README_dplyr` and `problems_dplyr` would do. Would it be possible for `revdep_check()` or a new variant to only report the new packages that have been checked since last time, and allow specifying the output file names? I guess this would involve recording a "reported" status in the db.


> the set of dependency versions is different if you don't do the old/new runs at the same time.

Could we have one library per checked package? Then we can reuse the exact same library when checking `new`.


> Also, this is not really a revdep check, but just checking a bunch of packages, one after the other. So I think it would be best to introduce a new function for this.

This is checking the reverse dependencies of R itself, rather than a package. I don't mind having a separate function for this though.

**Comment by gaborcsardi** [comment]
I don't mind having groups, but I am pretty sure that we don't need the tibbles. Sorry. They would be probably fine for you, but since I need to maintain this, they are not fine for me.

Yes, the DB needs some simple changes. 

> Could we have one library per checked package? Then we can reuse the exact same library when checking new.

We could do that, but currently the libraries are cleaned up after the check. Otherwise they get very big.

OK, so AFAICT we need two issues for these two features: groups and revdep checks against R.

**Comment by lionel-** [comment]
Should I open the new issues?

**Comment by gaborcsardi** [comment]
Thanks if you do that. Just refer here. If you are busy I can do that as well, mostly doing issues today....
