### ISSUE TITLE
Install all deps of revdeps first?

### ISSUE THREAD

**Issue by hadley** [r-lib/revdepcheck#33]
I think there are two advantages:

* crancache will have maximal information, so can easily use parallel downloads etc
* you're more robust to bad internet (i.e. #15)

You'd still do the install phase for each package to create the individual libraries, and to possible catch new updates in long running rev dep processes.

**Comment by gaborcsardi** [comment]
I was thinking about that, too, but I was worried that if it takes long, you won't see anything of the results. And that's potentially bad, because you might back off from revdep checks completely, because of some silly mistake. At least I do that and hate it that I have to wait several minutes until I notice it.

It is also true, that the downloaded packages go into the cache at least, so next time the startup of the actual checks will be much faster. So I don't mind this change, in the end.

Actually, now that I am looking over this code, we work out all the dependencies manually, anyway, because of a technicality with package libraries and dependencies of revdepcheck itself, so we know exactly what we need to install.

**Comment by krlmlr** [comment]
Want me to take a look?

**Comment by gaborcsardi** [comment]
> Could we enhance crancache to allow caching a package (including its binary version on Linux) without actually installing anything? 

Sure, I think there is an open issue for this.

>  I'm very much in favor of doing the download/compilation beforehand, and not in the individual workers, because
> 
> * it simplifies troubleshooting
> * it reduces concurrency on the crancache
> * it allows better parallelization, either with Ncpus = 8 or with MAKEVARS=-j 8

I will have to think about this, for sevaral reasons:
* In general I don't like it that we download everything up front, because we might spend a lot of time downloading without actually running anything.
* I don't like `Ncpus` either, because it uses `system`/`system2`, and it is hard to get the output, etc. and the installations should go to separate package libraries, anyway.
* You would need to rewrite much of the logic in `revdepcheck` to achieve this.

This said, it would be indeed great to avoid building the same binary package multiple times. So yes, let's think about this.

**Comment by krlmlr** [comment]
Actually, I'm suggesting to keep everything as is and to just add an optional crancache warming step.

**Comment by gaborcsardi** [comment]
So, with the async HTTP I am working on, we could keep downloading stuff while the checks are already running. This will take some time to implement in `revdepcheck`, though, but I think it will be superior both to the current solution and to downloading everything in the beginning.

**Comment by gaborcsardi** [comment]
Although most of the downloads already happen in subprocesses, anyway.

**Comment by HenrikBengtsson** [comment]
Just my $.02: Being able to download/install everything before launching tests will be helpful on for instance HPC environments where compute nodes have zero internet access (not uncommon).

**Comment by HenrikBengtsson** [comment]
I'm coming back to this as I now have a real case where I have to be able to download everything upfront because the actual compute nodes where checks will be running have zero-internet access (for security reasons).

I'm sure I can hack something together myself that populates the crancache with all package deps, but prefer to use something more official.  @krlmlr, I skimmed through your https://github.com/r-lib/revdepcheck/pull/53 - is that something worth trying out or was it just a prototype that might never happen?

**Comment by krlmlr** [comment]
Seems that we agreed that warming the cache isn't the best way to go. If there was an easy way to get the deps of all revdeps, you could simply call `crancache::install_packages()` with that list and a temporary library.

**Comment by HenrikBengtsson** [comment]
Thxs. If the local CRAN cache would be fully populated this way, will revdepcheck accept that there's no internet access / it cannot access online repositories, or will it produce an error (e.g. it'll try to update the cache)?

**Comment by gaborcsardi** [comment]
@HenrikBengtsson I would try setting `options(repos = c(CRAN = "<local-repo>"))` and if `revdepcheck` still goes online, then I'll fix that.

If you want to check BioC packages, then you would need to set the BioC repos as well.

**Comment by hadley** [comment]
I no longer think that this is important, and much else has changed in the last three years, so I'm going to close.

**Comment by HenrikBengtsson** [comment]
> I no longer think that this is important ...

Actually, being able to do this is critical to me and others with HPC environments where compute nodes don't have internet access (https://github.com/r-lib/revdepcheck/issues/33#issuecomment-338055272).  (There are other very techical reasons too)  I've implemented my own pre-install-all-revdep-children function that I call on a machine with internet access. When the crancache has been populated, I launch the revdep job on one of the compute nodes.

**Comment by HenrikBengtsson** [comment]
Didn't see @gaborcsardi:s comment:

> @HenrikBengtsson I would try setting options(repos = c(CRAN = "<local-repo>")) and if revdepcheck still goes online, then I'll fix that.

Yes, I do this personally and I do share the local CRAN & Bioconductor mirrors. It means you have to host _full_ mirrors of those and keep it in sync all the time for revdep checks to be valid.  Not all users are that savvy and or have the resources to full that off.

Another argument I have is that on systems like RHEL/CentOS, you often have dated C++ versions due to upstream distros are very conservative.  Running revdepcheck on such systems often result in several packages failing to install.  Being able to preinstall, allows you to make sure all deps installs before you launch all the checks.

Point is, having a revdepcheck function that prepopulate your crancache seems like a reasonable feature.

**Comment by gaborcsardi** [comment]
Yes, this makes sense, but I still find this use case too esoteric to support. Not a lot of people would want to run **revdep** checks on platforms that cannot compile CRAN packages.

Also, I think most probably there are workarounds. Maybe the easiest is to create a local partial CRAN mirror, the minicran and the drat packages can probably help with that.
